### PR TITLE
compute cell boundaries from cell ids

### PR DESCRIPTION
**Pull request by keewis**
This works pretty well for healpix, but not really for h3 (using `h3ronpy`): `h3ronpy.arrow.vector.cells_to_wkb_polygons` unnecessarily converts to WKB, and `h3ronpy.pandas.vector.cells_to_polygons` depends on `geopandas` (which for now I guess is fine, but we might want to figure out how to get rid of the dependency).

The API currently is based on properties, but we can just as well convert to methods.

### CODE REVIEW

**Comment by benbovy** [comment]
> h3ronpy.arrow.vector.cells_to_wkb_polygons unnecessarily converts to WKB, and h3ronpy.pandas.vector.cells_to_polygons depends on geopandas (which for now I guess is fine, but we might want to figure out how to get rid of the dependency).

Looking at the h3ronpy source, it looks like the latter wraps the former to create a geopandas GeoSeries from the WKB conversion, so it won't be very useful here.

I think it is fine (although not ideal) to convert to WKB, assuming that h3ronpy does that in a vectorized way. Given that shapely 2 can create polygon objects from WKB also in a vectorized way, both will already provide a reasonable level of performance I think.

**Comment by benbovy** [comment]
> The API currently is based on properties, but we can just as well convert to methods.

I think I'd vote for methods, since this might involve quite a bit of computation (not just returning some internal attribute or cached value).

**Comment by keewis** [comment]
I'm not sure how to best test this... @benbovy, do you have any ideas? Otherwise this should be ready for use.

**Comment by keewis** [comment]
looks like to be useful in all cases, we need to think about how poles and date line / prime meridian can be worked around with `shapely`: at the moment, if I ask `xvec` to select a bounding box based on the polygons for healpix cells, it may include cells that cross the date prime meridian (since healpix uses the 0-360 convention), even if the search area is on the other side of the globe. Not sure if H3 would have the same issue.

I guess to truly resolve this we need `spherely`, but I'm wondering if we can somehow work around this with `shapely`. I've tried manually applying the wrapping if:
- the polygon area is much bigger than the average cell area returned by `healpy`
- the minimum longitude is more than 300 degrees away from the maximum longitude

but this does not appear to work as well as I would like it to. Maybe we can instead map the longitudes so the vertices are in roughly the same distance from the cell centers.

Does anyone have any other ideas?

**Comment by keewis** [comment]
Even though we don't yet have a way to resolve this entirely, I'll go ahead and merge. Once we find out how to best represent spherical polygons we can open a new PR.

**Pull request merged**
