### PR TITLE
rename the primary grid parameter

### LINKED ISSUE #64: renaming the primary grid parameter from `resolution` to `level`
From #62:
> We've decided to go with `level` instead of resolution or `refinement_level` / `reflevel` etc. in the meeting, as the context is enough to disambiguate between other kinds of levels. In particular, "processing level" to me is a property of the data / dataset, not the grid (not sure what you're referring to with "maturity level", but if it has to do with the [data maturity](https://www.earthdata.nasa.gov/engage/open-data-services-and-software/data-and-information-policy/data-maturity-levels) I would also call that a property of the data or dataset, not the grid).

This issue is to track that change.

### PR DESCRIPTION
**Pull request by keewis**
- [x] closes #64

With the new name I don't really have an idea on how to describe the parameter in docstrings (level is not as easy to understand as resolution). We could describe it as

> the resolution / cell size of the grid

since grids don't have any information content, but not sure if that makes sense. Does anyone have any idea?

### CODE REVIEW

**Comment by strobpr** [comment]
a good phrasing for general description and understanding would be 'grid spacing (levels)'. A bit more special is 'cell size (levels)' as only applicable to cell grids (thus ok for DGGS) but not node grids (often coverages).

**Comment by benbovy** [comment]
I would simply say something like this:

```
level : int
    Grid hierarchical level. A higher value corresponds to a finer grid resolution
    with smaller cell areas. The number of cells covering the whole sphere usually
    grows exponentially (*) with increasing level values, ranging from 5-100 cells
    (level 0) to millions or billions of cells (level 10+).
```

(*) or as a power function?

**Comment by keewis** [comment]
I'd probably try to fit "depending on the specific grid" somewhere in the second sentence, but that's already really great (and as far as I can tell, exponential seems right because we're talking about $n^{\mathrm{level}}$, i.e. the base is constant but the power varies)

**Comment by benbovy** [comment]
I'd have been nice to return from a `DGGSInfo` instance a cell statistics table like those ones: [H3](https://h3geo.org/docs/core-library/restable/), [S2](http://s2geometry.io/resources/s2cell_statistics.html). But I don't think that the core libraries provide such thing via their API, unfortunately.

**Comment by keewis** [comment]
That could indeed be helpful.

For healpy there's `hp.nside2npix`, which in any case is `12 * 4**level`. As far as statistics like min/max/average area and min/max edge length go, this might be trickier but should not be impossible.

I'd say let's open a separate issue to discuss whether we add a method like that to `DGGSInfo`.

**Comment by strobpr** [comment]
Did you consider asking the [DGGS API experts](https://github.com/jerstlouis/ogcapi-discrete-global-grid-systems)?

**Comment by keewis** [comment]
assuming this is fine (we did have extensive discussion elsewhere), I'm going to merge this tomorrow.

**Comment by keewis** [comment]
merging. We can always improve later, should it become necessary.

**Pull request merged**
